/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zhuoweizhang_boardwalk_potato_LoadMe */

#ifndef _Included_net_zhuoweizhang_boardwalk_potato_LoadMe
#define _Included_net_zhuoweizhang_boardwalk_potato_LoadMe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_zhuoweizhang_boardwalk_potato_LoadMe
 * Method:    potatoExec
 * Signature: ([B[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_zhuoweizhang_boardwalk_potato_LoadMe_potatoExec
  (JNIEnv *, jclass, jbyteArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
